# Generated by Django 4.2.3 on 2023-07-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_users_date_of_birth_users_email_users_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='FirstTimeNutri',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='users',
            name='FirstTimeWorkout',
            field=models.BooleanField(default=True),
        ),
    ]
