# Generated by Django 4.2.3 on 2023-07-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionTab', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nutrition',
            old_name='title',
            new_name='email',
        ),
        migrations.AddField(
            model_name='nutrition',
            name='plan',
            field=models.TextField(null=True),
        ),
    ]
